### ISSUE TITLE
IPM Optimization

### ISSUE THREAD

**Issue by DanielCoelho112** [AutoMecUA/AutoMec-AD#105]
There are several ways that we can optimize the current IPM optimization, such as:

- Decrease code execution time
 Use matrix multiplication instead of loops
- Increase output quality image
 Verify intrinsic matrix
 Verify extrinsic matrix
 Look for bugs in the code

**Comment by DanielCoelho112** [comment]
The current IPM approach returns an image like this:

![Screenshot from 2021-11-18 21-45-28](https://user-images.githubusercontent.com/73063947/142501993-f3b469fc-3881-4eef-ad14-0018fff04407.png)

As you can see, the results are not optimal... And it took about 0.4 seconds to process each image...

**Comment by manuelgitgomes** [comment]
IPM package fully operational, although it seems results are worse. Further work here is needed.
![image](https://user-images.githubusercontent.com/58152228/144716372-e21a251f-9e5d-47ec-963b-02507c2e68d6.png)

**Comment by manuelgitgomes** [comment]
The IPM class now receives a dictionary with the camera pose and calculates the extrinsic matrix from it. The intrinsic matrix is retrieved from a ROS topic published by our vehicle. The results stay the same as they were before my last comment, so they are the same as @DanielCoelho112 described. Now, sliders will be added to the image in order to change values and certify our calculations are correct.

**Comment by Almeida-a** [comment]
As the commit complementary message describes (click the "..." button on that commit message), this slider implementation still has some problems.
They will be addressed perhaps at our next meeting, and the appropriate changes will be carried out to fix them.

PS: I also added a TODO and a FIXME in code to pinpoint those problems.

**Comment by Almeida-a** [comment]
The remaining code sections to be reviewed for optimization are the following functions:

- calculate_A_const
- calculate_extrinsic_matrix

**Comment by Almeida-a** [comment]
I found an interesting concept which we can use to carry out our optimization, which is profilers.
Here is a short [video](https://youtu.be/QSueV8MYtlw) on it, good for introducing that concept using pycharm.

**Comment by Almeida-a** [comment]
This [post](http://stackoverflow.com/questions/29433788/ddg#29435952) might fix our problem that is causing the slide bars not working.

**Comment by manuelgitgomes** [comment]
Regarding the sliders, this week I have implemented sliders on the signal recognition, as you can see here. You can see it and use it as a base for tour sliders!
https://github.com/AutoMecUA/AutoMec-AD/blob/af9cfbaa1e81c8af7e70101f7ada3dc392c0cdbe/signal_recognition/scripts/color_segmenter.py#L21-L50

**Comment by manuelgitgomes** [comment]
I have tried a different approach with better results than before. It's a mix between the one suggested by @inaciose and the one done by @DanielCoelho112. Instead of transforming all the image into the new coordinates, I chose only four points on the image to convert them. After finding the coordinates, use the `cv2.getperspectivetransform` function to create the output image. The process happens almost instantenously. Here you can see the selection of the corners and the resulting image.
![image](https://user-images.githubusercontent.com/58152228/146843586-16c71e66-5992-462b-af77-f6504a9fc521.png)

![image](https://user-images.githubusercontent.com/58152228/146843556-3f380389-9430-4b5d-99ca-5dd437b4274c.png)

Some things I yet cannot explain. The roll variable and the pitch variable seem to be switched. And the transform is not yet perfect. Feel free to comment.

**Comment by manuelgitgomes** [comment]
Retry rotation matrix calculation using
 https://github.com/GabrieleMicheli/PSR_A3/blob/0db343986b5595e496ab718c6abd6acc70b02232/p_group8_player/src/driver.py#L779-L791

**Comment by manuelgitgomes** [comment]
![image](https://user-images.githubusercontent.com/58152228/159359397-ce4eeb67-43e8-479f-aeb3-e5f2dbcb1b8d.png)
As seen, IPM is now much better. It does not, however, show the whole image. This might have to do with the parameter dsize in cv2.warpPerspective. 
Further work needs to be put here.

**Comment by manuelgitgomes** [comment]
Issue not a priority for current time.

**Comment by rospuye** [comment]
The problem seems to be that the `cv2.getPerspectiveTransform()` function only considers the cropping resulting from the four points in the input image for the output, as this image suggests.

![Screenshot from 2022-12-08 09-59-04](https://user-images.githubusercontent.com/66674322/206417591-0de597c8-c22c-4488-b5e8-dd151614d683.png)

It also explains why the output is rotated, altough that seems easy to fix. I'm not sure if the cropping problem can be solved through some input parameter of  `cv2.getPerspectiveTransform()` or if we need to use a different function altogether, but I will look into it. I found useful information [here](https://rospibot.azw.pt/inverse-perspective-mapping-em-python-usando-warpperspective/), [here](https://theailearner.com/tag/cv2-getperspectivetransform/) and [here](https://stackoverflow.com/questions/13063201/how-to-show-the-whole-image-when-using-opencv-warpperspective).

**Comment by manuelgitgomes** [comment]
[This](https://towardsdatascience.com/a-hands-on-application-of-homography-ipm-18d9e47c152f) approach seems like a valid one. It creates a plane on the floor and projects the points to the pixel image.
The image then receives a bilinear interpolation to tackle the pixel sparsity.

**Comment by PedroMS3** [comment]
If the opportunity rises this issue should be opened again, but only if new software members want to work on it
