### ISSUE TITLE
New power system for prometheus

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#148]
Study and develop a new power system for prometheus using 2 LiPo 2S batteries.

**Comment by andrefdre** [comment]
@manuelgitgomes is this issue related with what we were discussing last week?

**Comment by manuelgitgomes** [comment]
Exactly!

**Comment by andrefdre** [comment]
Okay, so to sum up what we discussed we thought about changing how the cameras will be powered, putting all the electronics in the same PCB and power the cameras with the same battery as the PWM signal generator. The other battery would power the motor.

**Comment by andrefdre** [comment]
We bought 1 step-down and 1 step-up since the ones we had weren't working, making it possible to have now 2 cameras working at the same time.
We also changed how the power is distributed, having 1 battery powering all the logical electronics(PWM generator and the 2 cameras) and another battery powering the motor. This will fix one problem we had in the competition, which was the battery depleting too quickly.
The ESP32 will still be powered by the computer and not the battery since it needs the usb cable for data transmission.
For this we made a new PCB that will have all the components and do the power distribution. It has 4 screw connectors to plug the camera wires and another 2 for the battery. This need correct labeling to prevent mistakes.
The new PCB can be seen in the picture below:
![WhatsApp Image 2022-11-23 at 20 51 06](https://user-images.githubusercontent.com/58526188/203646226-3ed95b73-4364-4dcd-a65d-e90a97b100b6.jpeg)
![Screenshot from 2022-11-23 17-56-05](https://user-images.githubusercontent.com/58526188/203646244-ee0f8c8f-492a-451b-89a4-6536fb4586d1.png)

**Comment by andrefdre** [comment]
A new task that is needed is to create a schematic of the new PCB so it is well documented and easy to do maintenance in the future

**Comment by andrefdre** [comment]
Schematic of the PCB board:
[Schematic.pdf](https://github.com/AutoMecUA/AutoMec-AD/files/10212419/Schematic.pdf)
![Schematic-1](https://user-images.githubusercontent.com/58526188/207167939-1701e4fc-057f-4694-a3fb-7561c829b032.png)

**Comment by manuelgitgomes** [comment]
This is already implemented
